services:
  ipsec-vpn-server:
    image: hwdsl2/ipsec-vpn-server:latest
    container_name: ipsec-vpn-server
    privileged: true
    environment:
      - VPN_IPSEC_PSK=${VPN_IPSEC_PSK}
      - VPN_USER=${VPN_USER}
      - VPN_PASSWORD=${VPN_PASSWORD}
      - VPN_ADDL_USERS=${VPN_ADDL_USERS}
      - VPN_ADDL_PASSWORDS=${VPN_ADDL_PASSWORDS}
    volumes:
      - ikev2-vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
    ports:
      - 500:500/udp
      - 4500:4500/udp
    restart: unless-stopped

volumes:
  ikev2-vpn-data:
    name: ikev2-vpn-data
