services:
  openvpn:
    image: ghcr.io/linuxserver/openvpn-as
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - INTERFACE=eth0 #optional
    volumes:
      - config:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    expose:
      - 943
    restart: unless-stopped
